// Vault content parsing helpers.
//
// Vault notes are stored in the `notes` table with their plaintext body
// in `notes.content`. When a note has attachments (images, videos, YouTube
// embeds, bookmarks, spreadsheets, generic links) we suffix the body
// with an `[ATTACHMENTS_JSON:[…]]` marker holding a JSON array. This
// keeps the schema flat (no second table, no jsonb column) while still
// letting the renderer reconstruct rich attachments at read time.
//
// Both the synthesis-layer DetailPanel / NeuronPanel and the Vault page
// itself rely on this parser, so it lives next to the storage helpers
// rather than inside any single page module — that would force a
// circular import when NeuronPanel pulls it in (SynthesisLayer
// → NeuronPanel → SynthesisLayer).

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type VaultAttachment = any;

export interface ParsedVaultContent {
  body: string;
  attachments: VaultAttachment[];
}

/** True when a URL points at Supabase Storage (public or signed). */
export function isSupabaseStorageUrl(url: string): boolean {
  return /supabase\.co\/storage\//i.test(String(url || ""));
}

/**
 * Strips auto-generated "File uploaded: …" / "[View File](url)" /
 * "[View Image](url)" / "[View](url)" / bare storage URLs / filename
 * (size) lines that upload code paths baked into note bodies. The
 * renderer already shows the file via the parsed attachment (image
 * preview, video player, file chip), and the title already carries
 * the filename — so the prose preamble plus the long Supabase storage
 * URL were pure visual noise inside the Vault neuron panel. Only
 * applied when the attachments marker is present, so user-typed plain
 * notes that happen to contain similar phrasing aren't touched.
 */
function stripAutoGeneratedBoilerplate(body: string): string {
  let out = body;
  out = out.replace(
    /^File uploaded:\s+[^\n]*(?:\n+Type:\s+[^\n]*)?(?:\n+Size:\s+[^\n]*)?/im,
    "",
  );
  out = out.replace(
    /\[(?:View(?:\s+(?:File|Image))?|Watch on YouTube)\]\([^)]+\)/gi,
    "",
  );
  // Bare storage URLs (older saves sometimes persisted the signed URL
  // as plain text instead of wrapping it in markdown).
  out = out.replace(/https?:\/\/[^\s)>\]"']*supabase\.co\/storage\/[^\s)>\]"']+/gi, "");
  // Upload pipeline body: "photo.jpg (1.23 MB)" — redundant with title
  // + attachment preview once the marker is present.
  out = out.replace(/^[^\n]+\(\s*[\d.]+\s*(?:KB|MB|GB)\s*\)\s*$/gim, "");
  out = out.replace(/^(?:Type|Size):\s[^\n]+$/gim, "");
  return out.replace(/\n{3,}/g, "\n\n").trim();
}

export function parseVaultContent(raw: string): ParsedVaultContent {
  const marker = "[ATTACHMENTS_JSON:";
  const start = raw.indexOf(marker);
  if (start === -1) return { body: raw.trim(), attachments: [] };
  const rawBody = raw.slice(0, start).trim();
  const body = stripAutoGeneratedBoilerplate(rawBody);
  try {
    const jsonStart = start + marker.length;
    let depth = 0;
    let jsonEnd = jsonStart;
    for (let i = jsonStart; i < raw.length; i++) {
      if (raw[i] === "[") depth++;
      else if (raw[i] === "]") {
        depth--;
        if (depth === 0) {
          jsonEnd = i;
          break;
        }
      }
    }
    const json = raw.slice(jsonStart, jsonEnd + 1);
    return { body, attachments: JSON.parse(json) };
  } catch {
    return { body, attachments: [] };
  }
}

// Best-effort resolution of an attachment's underlying Supabase Storage
// (bucket, path) tuple. Used by the renderer to refresh expired signed
// URLs. Three shapes are recognised:
//
//   1. Explicit `storagePath` (+ optional `storageBucket`) — written by
//      the modern upload flow which knows the bucket up front.
//   2. Public storage URL — `/storage/v1/object/public/<bucket>/<path>`.
//      Older attachments persisted the public link directly.
//   3. Signed storage URL — `/storage/v1/object/sign/<bucket>/<path>?…`.
//      Used to be returned by the legacy share flow; we strip the query
//      string and treat the path as the source of truth.
//
// Returns `null` for `data:` URLs (inline base64), external HTTPs links
// (YouTube, articles, etc.), or anything we can't parse into a bucket/
// path pair — the renderer falls back to the raw `url` in that case.
export function resolveStorageTarget(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  att: any,
): { bucket: string; path: string } | null {
  const explicitPath = String(att?.storagePath || "").trim();
  if (explicitPath) {
    return {
      bucket: String(att.storageBucket || "user-files").trim() || "user-files",
      path: explicitPath,
    };
  }
  const url = String(att?.url || "").trim();
  if (!url || url.startsWith("data:")) return null;
  try {
    const parsed = new URL(url);
    const p = parsed.pathname || "";
    const pubMatch = p.match(/\/storage\/v1\/object\/public\/([^/]+)\/(.+)$/);
    if (pubMatch) {
      return {
        bucket: decodeURIComponent(pubMatch[1]),
        path: decodeURIComponent(pubMatch[2]),
      };
    }
    const sigMatch = p.match(/\/storage\/v1\/object\/sign\/([^/]+)\/(.+)$/);
    if (sigMatch) {
      return {
        bucket: decodeURIComponent(sigMatch[1]),
        path: decodeURIComponent(sigMatch[2].split("?")[0]),
      };
    }
  } catch {
    /* not a URL — fall through to null */
  }
  return null;
}
