import { describe, it } from "node:test";
import assert from "node:assert/strict";
import {
  engineeringFileAccept,
  isEngineeringPath,
  summarizeEngineeringBuffer,
} from "./readEngineeringFile.js";

function asciiStl() {
  return new TextEncoder().encode(
    [
      "solid cube",
      "facet normal 0 0 1",
      "  outer loop",
      "    vertex 0 0 10",
      "    vertex 10 0 10",
      "    vertex 10 10 10",
      "  endloop",
      "endfacet",
      "endsolid cube",
      "",
    ].join("\n"),
  );
}

function binaryStl() {
  const faces = 1;
  const buf = new ArrayBuffer(84 + 50);
  const bytes = new Uint8Array(buf);
  const view = new DataView(buf);
  view.setUint32(80, faces, true);
  // one triangle in the XY plane, 10 mm on a side
  let off = 84 + 12;
  const verts = [
    [0, 0, 0],
    [10, 0, 0],
    [10, 10, 0],
  ];
  for (const [x, y, z] of verts) {
    view.setFloat32(off, x, true);
    view.setFloat32(off + 4, y, true);
    view.setFloat32(off + 8, z, true);
    off += 12;
  }
  return bytes;
}

describe("engineering file catalog", () => {
  it("recognizes CAD and mesh extensions", () => {
    assert.equal(isEngineeringPath("bracket.STEP"), true);
    assert.equal(isEngineeringPath("body.stl"), true);
    assert.equal(isEngineeringPath("notes.pdf"), false);
    assert.match(engineeringFileAccept(), /\.stl/);
    assert.match(engineeringFileAccept(), /\.step/);
  });
});

describe("summarizeEngineeringBuffer", () => {
  it("reads an ASCII STL bounding box and triangle count", () => {
    const brief = summarizeEngineeringBuffer(asciiStl(), "cube.stl");
    assert.match(brief, /Engineering file "cube.stl"/);
    assert.match(brief, /1 triangle/);
    assert.match(brief, /Bounding box/);
  });

  it("reads a binary STL", () => {
    const brief = summarizeEngineeringBuffer(binaryStl(), "part.stl");
    assert.match(brief, /binary mesh/);
    assert.match(brief, /1 triangle/);
  });

  it("extracts STEP product names", () => {
    const step = new TextEncoder().encode(
      "ISO-10303-21;\nHEADER;\nFILE_NAME('housing.step','2020-01-01T00:00:00',('a'),('a'),' ',' ',' ');\nENDSEC;\nDATA;\n#1=PRODUCT('Housing','Housing','',(#2));\n#3=CARTESIAN_POINT('',(0.,0.,0.));\nENDSEC;\nEND-ISO-10303-21;\n",
    );
    const brief = summarizeEngineeringBuffer(step, "housing.stp");
    assert.match(brief, /STEP CAD/);
    assert.match(brief, /Housing/);
  });

  it("lists OBJ groups", () => {
    const obj = new TextEncoder().encode("o femur\nv 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3\n");
    const brief = summarizeEngineeringBuffer(obj, "skel.obj");
    assert.match(brief, /femur/);
    assert.match(brief, /1 faces/);
  });

  it("reads G-code comments and a travel box", () => {
    const gcode = new TextEncoder().encode("; generated by LYKN\nG1 X10 Y0 Z0\nG1 X10 Y20 Z5\n");
    const brief = summarizeEngineeringBuffer(gcode, "part.gcode");
    assert.match(brief, /CNC toolpath/);
    assert.match(brief, /generated by LYKN/);
  });
});
