// ──────────────────────────────────────────────────────────────────────
// Connector catalog
//
// This is the single source of truth for "what can plug into LYKN."
// The Connections page renders cards from this list, but the same
// catalog is intended to drive provider adapters in the future
// (OAuth flows, sync workers, AI tool registrations, etc.).
//
// Status legend
//   "available"     – fully wired today (capture-only paths, RSS, etc.)
//   "beta"          – live but limited (e.g. share-target Phase 1 surfaces)
//   "soon"          – planned next, OAuth not yet built
//   "verification"  – planned but blocked on platform verification
//   "paid"          – planned but blocked on a paid API tier
//   "no-api"        – platform exposes nothing useful; capture-only path
// ──────────────────────────────────────────────────────────────────────

export const CONNECTOR_CATEGORIES = [
  {
    id: "social",
    label: "Social & Content",
    description: "Auto-pull saved posts, liked videos, bookmarks, and feeds.",
  },
  {
    id: "productivity",
    label: "Productivity & Docs",
    description: "Bring your notes, docs, calendars, and tasks into the vault.",
  },
  {
    id: "design",
    label: "Design & Media",
    description: "Reference design files, recordings, and creative assets.",
  },
  {
    id: "read",
    label: "Read-it-later & Highlights",
    description: "Articles, books, and highlights from across the web.",
  },
  {
    id: "music",
    label: "Music & Audio",
    description: "Saved tracks, albums, podcasts.",
  },
  {
    id: "capture",
    label: "Universal Capture",
    description: "Catch-all surfaces that work on any platform or device.",
  },
  {
    id: "automation",
    label: "Automation & AI",
    description: "Wire LYKN into agent ecosystems and automation tools.",
  },
];

export const CONNECTORS = [
  // ── Social & Content ─────────────────────────────────────────────
  {
    id: "youtube",
    category: "social",
    name: "YouTube",
    domain: "youtube.com",
    color: "#FF0033",
    auth: "Google OAuth",
    pulls: ["Liked videos"],
    realtime: "Polling (60 min)",
    status: "verification",
    statusLabel: "Pending Google review",
    summary: "Auto-imports every video you Like. Pre-verification: Google Cloud test users only.",
  },
  {
    id: "pinterest",
    category: "social",
    name: "Pinterest",
    domain: "pinterest.com",
    color: "#E60023",
    auth: "Pinterest OAuth",
    pulls: ["All your pins"],
    realtime: "Polling (60 min)",
    status: "available",
    statusLabel: "Live",
    summary: "Auto-imports every pin you save. Read-only.",
  },
  {
    id: "x",
    category: "social",
    name: "X (Twitter)",
    domain: "x.com",
    color: "#000000",
    auth: "OAuth 2.0 PKCE",
    pulls: ["Bookmarks"],
    realtime: "Polling (60 min)",
    status: "paid",
    statusLabel: "Requires X API Basic ($200/mo)",
    summary:
      "Auto-imports every tweet you Bookmark. The /bookmarks endpoint requires X API Basic tier; OAuth itself works on Free.",
  },
  {
    id: "reddit",
    category: "social",
    name: "Reddit",
    domain: "reddit.com",
    color: "#FF4500",
    auth: "Reddit OAuth",
    pulls: ["Saved posts & comments"],
    realtime: "Polling (60 min)",
    status: "available",
    statusLabel: "Live",
    summary: "Auto-imports every post and comment you save on Reddit. Read-only.",
  },
  {
    id: "bluesky",
    category: "social",
    name: "Bluesky",
    domain: "bsky.app",
    color: "#0085FF",
    auth: "AT Protocol",
    pulls: ["Likes", "Lists", "Posts"],
    realtime: "Streaming firehose",
    status: "soon",
    summary: "Bluesky's open API exposes likes and lists cleanly.",
  },
  {
    id: "mastodon",
    category: "social",
    name: "Mastodon",
    domain: "joinmastodon.org",
    color: "#6364FF",
    auth: "Per-instance OAuth",
    pulls: ["Favorites", "Bookmarks"],
    realtime: "Streaming",
    status: "soon",
    summary: "Pulls your favorites and bookmarks from any Mastodon instance.",
  },
  {
    id: "instagram",
    category: "social",
    name: "Instagram",
    domain: "instagram.com",
    color: "#E1306C",
    auth: "n/a",
    pulls: ["Capture-only via Share button"],
    realtime: "On share",
    status: "no-api",
    statusLabel: "Capture only",
    summary:
      "Instagram doesn't expose Saved posts via API. Use the Save to LYKN button or share sheet.",
  },
  {
    id: "tiktok",
    category: "social",
    name: "TikTok",
    domain: "tiktok.com",
    color: "#010101",
    auth: "n/a",
    pulls: ["Capture-only via Share button"],
    realtime: "On share",
    status: "no-api",
    statusLabel: "Capture only",
    summary:
      "TikTok's API doesn't expose Favorites. Use the Save to LYKN button or share sheet.",
  },
  {
    id: "facebook",
    category: "social",
    name: "Facebook",
    domain: "facebook.com",
    color: "#1877F2",
    auth: "n/a",
    pulls: ["Capture-only via Share button"],
    realtime: "On share",
    status: "no-api",
    statusLabel: "Capture only",
    summary:
      "Facebook's Graph API doesn't expose Saved items. Use the Save to LYKN button or share sheet.",
  },

  // ── Productivity & Docs ──────────────────────────────────────────
  {
    id: "notion",
    category: "productivity",
    name: "Notion",
    domain: "notion.so",
    color: "#000000",
    auth: "Notion OAuth",
    pulls: ["Pages you grant access to"],
    realtime: "Polling (60 min)",
    status: "available",
    statusLabel: "Live",
    summary: "Workspace pages you share with LYKN become searchable inside the Vault.",
  },
  {
    id: "google-drive",
    category: "productivity",
    name: "Google Drive",
    domain: "drive.google.com",
    color: "#1FA463",
    auth: "Google OAuth",
    pulls: ["Starred files (metadata only)"],
    realtime: "Polling (60 min)",
    status: "verification",
    statusLabel: "Pending Google review",
    summary: "Surfaces every starred file in your Drive. Pre-verification: Google Cloud test users only.",
  },
  {
    id: "google-calendar",
    category: "productivity",
    name: "Google Calendar",
    domain: "calendar.google.com",
    color: "#4285F4",
    auth: "Google OAuth",
    pulls: ["Upcoming events (30 days)"],
    realtime: "Polling (60 min)",
    status: "verification",
    statusLabel: "Pending Google review",
    summary: "Imports events from your primary calendar. Pre-verification: Google Cloud test users only.",
  },
  {
    id: "gmail",
    category: "productivity",
    name: "Gmail",
    domain: "mail.google.com",
    color: "#EA4335",
    auth: "Google OAuth",
    pulls: ["Starred emails"],
    realtime: "Polling (60 min)",
    status: "verification",
    statusLabel: "Pending Google review (restricted scope)",
    summary: "Captures every starred email. Pre-verification: Google Cloud test users only.",
  },
  {
    id: "outlook-365",
    category: "productivity",
    name: "Microsoft 365",
    domain: "microsoft365.com",
    color: "#0078D4",
    auth: "Microsoft Graph",
    pulls: ["Flagged Outlook emails"],
    realtime: "Polling (60 min)",
    status: "available",
    statusLabel: "Live",
    summary: "Auto-imports every email you flag in Outlook. Read-only.",
  },
  {
    id: "slack",
    category: "productivity",
    name: "Slack",
    domain: "slack.com",
    color: "#4A154B",
    auth: "Slack OAuth",
    pulls: ["Saved messages"],
    realtime: "Polling (60 min)",
    status: "available",
    statusLabel: "Live",
    summary: "Auto-imports every message you save in Slack. Read-only, single workspace per connection.",
  },
  {
    id: "github",
    category: "productivity",
    name: "GitHub",
    domain: "github.com",
    color: "#181717",
    auth: "GitHub OAuth",
    pulls: ["Starred repos"],
    realtime: "Polling (60 min)",
    status: "available",
    statusLabel: "Live",
    summary: "Auto-imports every repo you star into your Vault. Read-only, no posts.",
  },
  {
    id: "linear",
    category: "productivity",
    name: "Linear",
    domain: "linear.app",
    color: "#5E6AD2",
    auth: "Linear OAuth",
    pulls: ["Issues assigned to you"],
    realtime: "Polling (60 min)",
    status: "available",
    statusLabel: "Live",
    summary: "Open issues assigned to you become actionable cards in your Vault.",
  },
  {
    id: "todoist",
    category: "productivity",
    name: "Todoist",
    domain: "todoist.com",
    color: "#E44232",
    auth: "Todoist OAuth",
    pulls: ["Active tasks"],
    realtime: "Polling (60 min)",
    status: "available",
    statusLabel: "Live",
    summary: "Active tasks land in your Vault alongside everything else you capture.",
  },
  {
    id: "trello",
    category: "productivity",
    name: "Trello",
    domain: "trello.com",
    color: "#0079BF",
    auth: "Trello OAuth",
    pulls: ["Cards", "Boards"],
    realtime: "Webhooks",
    status: "soon",
    summary: "Cards from boards you grant access to.",
  },

  // ── Design & Media ───────────────────────────────────────────────
  {
    id: "figma",
    category: "design",
    name: "Figma",
    domain: "figma.com",
    color: "#F24E1E",
    auth: "Figma OAuth",
    pulls: ["Files", "Comments", "Thumbnails"],
    realtime: "Webhooks",
    status: "soon",
    summary: "Reference Figma files inside the vault and canvas.",
  },
  {
    id: "canva",
    category: "design",
    name: "Canva",
    domain: "canva.com",
    color: "#00C4CC",
    auth: "Canva Connect API",
    pulls: ["Designs", "Exports"],
    realtime: "Polling",
    status: "soon",
    summary: "Your Canva designs available as previews and exports.",
  },
  {
    id: "loom",
    category: "design",
    name: "Loom",
    domain: "loom.com",
    color: "#625DF5",
    auth: "Loom OAuth",
    pulls: ["Videos", "Transcripts"],
    realtime: "Polling",
    status: "soon",
    summary: "Video recordings with transcripts ready for AI search.",
  },
  {
    id: "vimeo",
    category: "design",
    name: "Vimeo",
    domain: "vimeo.com",
    color: "#1AB7EA",
    auth: "Vimeo OAuth",
    pulls: ["Liked videos"],
    realtime: "Polling (60 min)",
    status: "available",
    statusLabel: "Live",
    summary: "Auto-imports every video you Like on Vimeo. Read-only.",
  },
  {
    id: "dribbble",
    category: "design",
    name: "Dribbble",
    domain: "dribbble.com",
    color: "#EA4C89",
    auth: "Dribbble OAuth",
    pulls: ["Liked shots"],
    realtime: "Polling (60 min)",
    status: "available",
    statusLabel: "Live",
    summary: "Auto-imports every shot you Like on Dribbble. Read-only.",
  },
  {
    id: "behance",
    category: "design",
    name: "Behance",
    domain: "behance.net",
    color: "#1769FF",
    auth: "Adobe OAuth",
    pulls: ["Appreciated projects", "Collections"],
    realtime: "Polling",
    status: "soon",
    summary: "Appreciated projects and collections from Behance.",
  },

  // ── Read-it-later & Highlights ────────────────────────────────────
  {
    id: "readwise",
    category: "read",
    name: "Readwise",
    domain: "readwise.io",
    color: "#0F0F0F",
    auth: "API token",
    pulls: ["Highlights", "Articles", "Books"],
    realtime: "Webhooks",
    status: "soon",
    summary:
      "The single best aggregator for highlights — Kindle, Apple Books, web articles.",
  },
  {
    id: "raindrop",
    category: "read",
    name: "Raindrop.io",
    domain: "raindrop.io",
    color: "#0B7CFF",
    auth: "Raindrop OAuth",
    pulls: ["All bookmarks"],
    realtime: "Polling (60 min)",
    status: "available",
    statusLabel: "Live",
    summary: "Every bookmark you save in Raindrop flows into your Vault. Read-only.",
  },
  {
    id: "instapaper",
    category: "read",
    name: "Instapaper",
    domain: "instapaper.com",
    color: "#1F1F1F",
    auth: "OAuth (xAuth)",
    pulls: ["Saved articles", "Highlights"],
    realtime: "Polling",
    status: "soon",
    summary: "Saved articles and highlights from Instapaper.",
  },
  {
    id: "matter",
    category: "read",
    name: "Matter",
    domain: "hq.getmatter.com",
    color: "#1B1B1B",
    auth: "API key",
    pulls: ["Saved articles", "Highlights"],
    realtime: "Polling",
    status: "soon",
    summary: "Articles and highlights from Matter.",
  },
  {
    id: "pocket",
    category: "read",
    name: "Pocket",
    domain: "getpocket.com",
    color: "#EF4056",
    auth: "Consumer key",
    pulls: ["Archive (one-time import only)"],
    realtime: "Import",
    status: "no-api",
    statusLabel: "Sunsetting",
    summary:
      "Mozilla is shutting Pocket down. Use the import path to bring your archive into LYKN.",
  },

  // ── Music & Audio ────────────────────────────────────────────────
  {
    id: "spotify",
    category: "music",
    name: "Spotify",
    domain: "spotify.com",
    color: "#1DB954",
    auth: "Spotify OAuth",
    pulls: ["Liked Songs"],
    realtime: "Polling (60 min)",
    status: "available",
    statusLabel: "Live",
    summary: "Auto-imports every song you Like into your Vault. Read-only.",
  },
  {
    id: "apple-music",
    category: "music",
    name: "Apple Music",
    domain: "music.apple.com",
    color: "#FA243C",
    auth: "MusicKit JS",
    pulls: ["Library", "Playlists"],
    realtime: "Polling",
    status: "soon",
    summary: "Your library and playlists from Apple Music.",
  },
  {
    id: "soundcloud",
    category: "music",
    name: "SoundCloud",
    domain: "soundcloud.com",
    color: "#FF5500",
    auth: "SoundCloud OAuth",
    pulls: ["Likes", "Playlists"],
    realtime: "Polling",
    status: "soon",
    summary: "Liked tracks and playlists from SoundCloud.",
  },

  // ── Universal Capture ────────────────────────────────────────────
  // First-party capture surfaces — no domain, no brand logo. Renders the
  // Lucide fallback in BrandIcon.
  {
    id: "share-target",
    category: "capture",
    name: "Mobile Share Sheet",
    color: "#111827",
    auth: "PWA install",
    pulls: ["Anything you tap Share on"],
    realtime: "On share",
    status: "beta",
    statusLabel: "Live",
    summary:
      "Add LYKN to your phone's home screen and it appears in every app's Share sheet.",
  },
  {
    id: "browser-extension",
    category: "capture",
    name: "Browser Extension",
    color: "#111827",
    auth: "Local install",
    pulls: ["Any page, link, image, or video"],
    realtime: "On click",
    status: "beta",
    statusLabel: "Live",
    summary:
      "One-click save from any website with a toolbar button or right-click menu.",
  },
  {
    id: "bookmarklet",
    category: "capture",
    name: "Bookmarklet",
    color: "#111827",
    auth: "Drag to bookmarks bar",
    pulls: ["Any open page"],
    realtime: "On click",
    status: "beta",
    statusLabel: "Live",
    summary:
      "A draggable bookmark that saves the current page to LYKN with one click. No install.",
  },
  {
    id: "email-to-vault",
    category: "capture",
    name: "Email to Vault",
    color: "#111827",
    auth: "Per-user inbound address",
    pulls: ["Anything emailed to your alias"],
    realtime: "Inbound webhook",
    status: "soon",
    summary:
      "A unique email address for your vault. Forward newsletters, share links, anything.",
  },
  {
    id: "rss",
    category: "capture",
    name: "RSS / Atom feeds",
    color: "#FF6600",
    auth: "None",
    pulls: ["Any blog, podcast, Substack, etc."],
    realtime: "Polling",
    status: "beta",
    statusLabel: "Live",
    summary:
      "One connector covers Substack, Medium, blogs, podcasts, YouTube channels, GitHub releases.",
  },

  // ── Automation & AI ──────────────────────────────────────────────
  {
    id: "mcp",
    category: "automation",
    name: "MCP Servers",
    color: "#0F172A",
    auth: "Per-server config",
    pulls: ["Any MCP-compatible tool"],
    realtime: "Live",
    status: "soon",
    summary:
      "Connect any Model Context Protocol server. Frees us from writing one adapter per tool.",
  },
  {
    id: "zapier",
    category: "automation",
    name: "Zapier",
    domain: "zapier.com",
    color: "#FF4A00",
    auth: "Zapier app",
    pulls: ["8000+ apps via triggers"],
    realtime: "On trigger",
    status: "soon",
    summary:
      "Wire LYKN into Zapier. Triggers fire when items are saved, actions create vault items.",
  },
  {
    id: "make",
    category: "automation",
    name: "Make.com",
    domain: "make.com",
    color: "#6D00CC",
    auth: "Make app",
    pulls: ["Any Make scenario"],
    realtime: "On trigger",
    status: "soon",
    summary: "Same as Zapier, for Make.com workflows.",
  },
  {
    id: "n8n",
    category: "automation",
    name: "n8n",
    domain: "n8n.io",
    color: "#EA4B71",
    auth: "n8n node",
    pulls: ["Self-hosted automations"],
    realtime: "On trigger",
    status: "soon",
    summary: "An n8n node so you can self-host LYKN automations.",
  },
];

export const CONNECTOR_STATUSES = {
  available: { label: "Available", tone: "emerald" },
  beta: { label: "Live", tone: "emerald" },
  soon: { label: "Coming soon", tone: "blue" },
  verification: { label: "In review", tone: "amber" },
  paid: { label: "Paid API only", tone: "amber" },
  "no-api": { label: "Capture only", tone: "neutral" },
};
