-- 118_collation_version_refresh.sql
--
-- [2026-07-13] Ran ALTER DATABASE postgres REFRESH COLLATION VERSION to
-- resolve the OS/ICU collation version mismatch warning on the production
-- Supabase instance. The refresh itself was executed ad-hoc in the SQL
-- Editor on 2026-07-13 (confirmed successful, no errors); this file records
-- it in the migration sequence and is safe to re-run.
--
-- Background: the underlying OS libc/ICU library was upgraded (typically by
-- a Supabase platform maintenance/upgrade), so the collation version Postgres
-- recorded at initdb time no longer matched the runtime version. The refresh
-- updates the recorded version. If any text data was inserted while the
-- versions were mismatched, indexes on text columns can theoretically be
-- corrupted and should be rebuilt (see verification queries below).

ALTER DATABASE postgres REFRESH COLLATION VERSION;

-- ---------------------------------------------------------------------------
-- Verification (run in SQL Editor; both queries should return zero rows
-- with a mismatch after the refresh):
--
--   -- Database-level default collation (PG15+)
--   SELECT datname,
--          datcollversion            AS recorded,
--          pg_database_collation_actual_version(oid) AS actual
--   FROM pg_database
--   WHERE datcollversion IS DISTINCT FROM
--         pg_database_collation_actual_version(oid);
--
--   -- Individual non-default collations
--   SELECT collname,
--          collversion               AS recorded,
--          pg_collation_actual_version(oid) AS actual
--   FROM pg_collation
--   WHERE collprovider <> 'd'
--     AND collversion IS NOT NULL
--     AND collversion IS DISTINCT FROM pg_collation_actual_version(oid);
--
-- If individual collations still mismatch, refresh each one:
--   ALTER COLLATION pg_catalog."<collname>" REFRESH VERSION;
--
-- ---------------------------------------------------------------------------
-- Rebuild (ONLY if collation warnings keep appearing in the logs after the
-- refresh, or if text data was written while versions were mismatched).
-- REINDEX is heavy; take a backup first and prefer CONCURRENTLY in prod:
--
--   -- Targeted (per warning in logs):
--   REINDEX INDEX CONCURRENTLY <index_name>;
--   REINDEX TABLE CONCURRENTLY <table_name>;
--
--   -- Materialized views that select text columns:
--   REFRESH MATERIALIZED VIEW <view_name>;
