/**
 * Voice client-tool names. Must stay in lockstep with LYKN_VOICE_TOOL_NAMES
 * in mcp-tools/voiceTools.js. voiceTools.test.mjs asserts that.
 */
export const VOICE_CLIENT_TOOL_NAMES = [
  "web_search",
  "web_fetch",
  "memory_list",
  "memory_read",
  "memory_patch",
  "memory_create",
  "memory_forget",
  "list_projects",
  "get_project_state",
  "set_active_project",
  "create_project",
  "update_project",
  "resolve_project",
  "update_project_state",
  "delete_project",
  "merge_projects",
  "get_recent_activity",
  "create_reminder",
  "list_reminders",
  "update_reminder",
  "create_event",
  "list_events",
  "update_event",
  "delete_event",
  "create_todo",
  "list_todos",
  "update_todo",
  "delete_todo",
  "build_with_cursor",
  "check_cursor_build",
  "save_to_vault",
  "save_link_to_vault",
  "add_to_project",
  "ask_bot",
  "browser_agent",
  "update_voice_instructions",
  "list_apps",
  "call_app",
  "get_current_time",
  "calculate",
  "symbolic_math",
  "run_python",
  "run_code",
  "http_request",
  "get_preferences",
  "update_preference",
  "list_steward_items",
  "create_steward_item",
  "update_steward_item",
  "write_document",
  "save_file_to_vault",
  "open_app",
  "open_settings",
  "generate_image",
  "process_image",
  "generate_speech",
  "transcribe_audio",
  "parse_document",
  "translate",
  "generate_chart",
  "generate_diagram",
  "build_spreadsheet",
  "build_template",
  "build_react_artifact",
  "render_video",
  "manage_file",
  "local_list_dir",
  "local_read_file",
  "local_search_files",
  "local_pull_file",
  "local_write_file",
  "local_edit_file",
  "local_run_command",
  "local_synced_folders",
  "local_running_apps",
  "local_read_app",
  "local_open_app",
  "local_open_path",
  "local_organize_desktop",
] as const;

export const VOICE_TOOL_STATUS_COPY: Record<string, string> = {
  web_search: "Searching the web…",
  web_fetch: "Reading the page…",
  list_projects: "Looking through your projects…",
  get_project_state: "Checking the project…",
  set_active_project: "Switching projects…",
  create_project: "Starting a new project…",
  update_project: "Updating the project…",
  resolve_project: "Finding the project…",
  update_project_state: "Updating the project…",
  delete_project: "Removing the project…",
  merge_projects: "Merging the projects…",
  get_recent_activity: "Catching up on recent activity…",
  create_reminder: "Setting a reminder…",
  list_reminders: "Checking your reminders…",
  update_reminder: "Updating the reminder…",
  create_event: "Adding to your calendar…",
  list_events: "Checking your calendar…",
  update_event: "Updating the event…",
  delete_event: "Removing the event…",
  create_todo: "Adding a to-do…",
  list_todos: "Checking your to-dos…",
  update_todo: "Updating the to-do…",
  delete_todo: "Removing the to-do…",
  build_with_cursor: "Kicking off the build…",
  check_cursor_build: "Checking the build…",
  save_to_vault: "Saving to your vault…",
  save_link_to_vault: "Saving the link to your vault…",
  add_to_project: "Adding it to the project…",
  ask_bot: "Sending your bot…",
  browser_agent: "Sending it to the browser…",
  update_voice_instructions: "Adjusting how it sounds…",
  get_current_time: "Checking the time…",
  calculate: "Crunching the numbers…",
  symbolic_math: "Working through the math…",
  run_python: "Running the analysis…",
  run_code: "Running the code…",
  http_request: "Gathering resources…",
  get_preferences: "Checking your preferences…",
  update_preference: "Updating your settings…",
  list_steward_items: "Checking the overnight queue…",
  create_steward_item: "Adding it to the queue…",
  update_steward_item: "Updating the queue…",
  write_document: "Writing it out…",
  save_file_to_vault: "Saving the file…",
  open_app: "Opening it…",
  open_settings: "Opening your settings…",
  generate_image: "Creating the image…",
  process_image: "Looking at the image…",
  generate_speech: "Generating the audio…",
  transcribe_audio: "Transcribing the audio…",
  parse_document: "Reading the document…",
  translate: "Translating…",
  generate_chart: "Building the chart…",
  generate_diagram: "Drawing the diagram…",
  build_spreadsheet: "Building the spreadsheet…",
  build_template: "Building the template…",
  build_react_artifact: "Building it…",
  render_video: "Rendering the video…",
  manage_file: "Preparing the file…",
  local_list_dir: "Looking through your files…",
  local_read_file: "Reading the file…",
  local_search_files: "Searching your files…",
  local_pull_file: "Pulling it in…",
  local_write_file: "Writing the file…",
  local_edit_file: "Editing the file…",
  local_run_command: "Running it on your Mac…",
  local_synced_folders: "Checking your synced folders…",
  local_running_apps: "Checking your open apps…",
  local_read_app: "Reading the app…",
  local_open_app: "Opening the app…",
  local_open_path: "Opening it…",
  local_organize_desktop: "Tidying your desktop…",
  list_apps: "Checking your connected apps…",
  call_app: "Talking to the app…",
};
