"use strict";

const OVERLAY_WIDTH = 520;
const OVERLAY_SIDE_WIDTH = 300;
const OVERLAY_WATCH_SIDE_WIDTH = 360;
const OVERLAY_MAX_WIDTH = OVERLAY_WIDTH + OVERLAY_WATCH_SIDE_WIDTH;
const OVERLAY_MIN_HEIGHT = 82;
const OVERLAY_BOTTOM_MARGIN = 90;
const GLASS_CORNER_RADIUS = 16;
const OVERLAY_BUBBLE = 54;
const OVERLAY_ACTIVATABLE_FOR_DROPS = false;
const MENU_WIDTH = 248;
const MENU_GAP = 12;
const MENU_MIN_HEIGHT = 120;
const MENU_MAX_HEIGHT = 480;
const PICKER_WIDTH = 200;
const PICKER_MIN_HEIGHT = 60;
const PICKER_MAX_HEIGHT = 420;
const LIVE_WIDTH = 420;
const LIVE_HEIGHT = 520;
const PANEL_MIN_HEIGHT = 120;
const PANEL_MAX_HEIGHT = 560;
const UPDATE_REPROMPT_MS = 30 * 60 * 1000;

module.exports = {
  OVERLAY_WIDTH,
  OVERLAY_SIDE_WIDTH,
  OVERLAY_WATCH_SIDE_WIDTH,
  OVERLAY_MAX_WIDTH,
  OVERLAY_MIN_HEIGHT,
  OVERLAY_BOTTOM_MARGIN,
  GLASS_CORNER_RADIUS,
  OVERLAY_BUBBLE,
  OVERLAY_ACTIVATABLE_FOR_DROPS,
  MENU_WIDTH,
  MENU_GAP,
  MENU_MIN_HEIGHT,
  MENU_MAX_HEIGHT,
  PICKER_WIDTH,
  PICKER_MIN_HEIGHT,
  PICKER_MAX_HEIGHT,
  LIVE_WIDTH,
  LIVE_HEIGHT,
  PANEL_MIN_HEIGHT,
  PANEL_MAX_HEIGHT,
  UPDATE_REPROMPT_MS,
};
