import { useEffect, useRef, useState } from "react";
import { Volume2, VolumeX } from "lucide-react";
import type { RealtimeVoiceState } from "@/hooks/useRealtimeVoice";
import VoiceTechOrb from "@/components/lyknChat/VoiceTechOrb";

interface WakeVoiceTourPreviewProps {
  active?: boolean;
  /**
   * When false, the preview is purely the Voice Mode UI: no "Hear it" toggle
   * and audio can never play. Used for the static phone mockup on the landing
   * page; the standalone voice feature card keeps audio (default true).
   */
  allowAudio?: boolean;
}

// Same status copy the real Voice Mode overlay shows beneath the orb
// (LyknChatVoiceModeEleven STATUS_COPY).
const STATUS_COPY: Partial<Record<RealtimeVoiceState, string>> = {
  idle: "Paused",
  connecting: "Connecting…",
  listening: "Listening…",
  thinking: "Thinking…",
  speaking: "Speaking…",
};

// A gentle scripted loop so the real orb feels alive in the walkthrough
// when audio is OFF (no mic / WebSocket session).
const SILENT_CYCLE: { state: RealtimeVoiceState; ms: number }[] = [
  { state: "connecting", ms: 1400 },
  { state: "listening", ms: 3200 },
  { state: "thinking", ms: 1600 },
  { state: "speaking", ms: 4200 },
];

// The scripted demo conversation. Every line is a real ElevenLabs clip
// (generated by scripts/generate-wake-voice-audio.mjs): LYKN uses the SAME
// voice as the live Voice agent, while the human turns use a DIFFERENT voice
// on purpose so it's unmistakably a scripted demo, not the user's own mic.
interface ScriptLine {
  role: "user" | "lykn";
  text: string;
  src?: string;
  /** Set on the FIRST line of each exchange — labels + separates the section. */
  section?: string;
}

const SCRIPT: ScriptLine[] = [
  // 1 — Your day
  {
    role: "user",
    section: "Your day",
    text: "Morning LYKN, what's on my plate today?",
    src: "/wake-demo/voice/user-1.mp3",
  },
  {
    role: "lykn",
    text: "You've got the investor call at 2, and your Q3 brief is still open.",
    src: "/wake-demo/voice/lykn-1.mp3",
  },
  // 2 — Memory recall
  {
    role: "user",
    section: "Memory recall",
    text:
      "Can you give me a report on what Mark thought about our ICP personas?",
    src: "/wake-demo/voice/user-2.mp3",
  },
  {
    role: "lykn",
    text:
      "From Mark's notes, he liked the core personas, but wants the enterprise one split into a founder buyer and an IT approver.",
    src: "/wake-demo/voice/lykn-2.mp3",
  },
  // 3 — Business pulse
  {
    role: "user",
    section: "Business pulse",
    text: "Alright, how's the app doing this morning?",
    src: "/wake-demo/voice/user-3.mp3",
  },
  {
    role: "lykn",
    text:
      "Looking strong. You added 42 new users overnight, up 18%, with activation holding steady and no error spikes. One thing to flag, though: Emily sent over a bug report by email this morning.",
    src: "/wake-demo/voice/lykn-3.mp3",
  },
  // 4 — Inbox
  {
    role: "user",
    section: "Inbox",
    text: "What was that bug report email about?",
    src: "/wake-demo/voice/user-4.mp3",
  },
  {
    role: "lykn",
    text:
      "Emily reported that the dashboard export button does nothing in Safari: no file downloads and no error appears. It works fine in Chrome, so it looks browser-specific.",
    src: "/wake-demo/voice/lykn-4.mp3",
  },
  // 5 — Cloud agent
  {
    role: "user",
    section: "Cloud agent",
    text: "Have a cloud agent fix that bug in Cursor and open a pull request.",
    src: "/wake-demo/voice/user-5.mp3",
  },
  {
    role: "lykn",
    text:
      "On it. A cloud agent is fixing it in Cursor and will open a PR for your review.",
    src: "/wake-demo/voice/lykn-5.mp3",
  },
  // 6 — Hands-free
  {
    role: "user",
    section: "Hands-free",
    text: "Perfect. Keep working on the Q3 brief while I drive.",
    src: "/wake-demo/voice/user-6.mp3",
  },
  {
    role: "lykn",
    text: "Will do. I'll have it ready for you when you arrive.",
    src: "/wake-demo/voice/lykn-6.mp3",
  },
];

// Fallback reading time if a clip can't load.
const fallbackLineMs = (text: string) =>
  Math.max(1600, text.split(/\s+/).filter(Boolean).length * 360);

/**
 * Walkthrough preview for Voice Mode. Renders the SAME VoiceTechOrb the real
 * Voice Mode overlay uses, in the same centered chrome. Audio is OFF by
 * default; a speaker toggle plays the scripted conversation, with LYKN voiced
 * by real ElevenLabs clips, and drives the orb state from playback.
 */
export default function WakeVoiceTourPreview({
  active = true,
  allowAudio = true,
}: WakeVoiceTourPreviewProps) {
  const [audioOn, setAudioOn] = useState(false);
  const [orbState, setOrbState] = useState<RealtimeVoiceState>("listening");
  const [micLevel, setMicLevel] = useState(0);
  const [lineIdx, setLineIdx] = useState(0);
  const [silentStep, setSilentStep] = useState(0);
  const rafRef = useRef<number | null>(null);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  // ── Silent idle animation (audio off) ────────────────────────────────
  useEffect(() => {
    if (audioOn || !active) return undefined;
    const { ms } = SILENT_CYCLE[silentStep];
    setOrbState(SILENT_CYCLE[silentStep].state);
    const id = window.setTimeout(
      () => setSilentStep((s) => (s + 1) % SILENT_CYCLE.length),
      ms,
    );
    return () => window.clearTimeout(id);
  }, [audioOn, active, silentStep]);

  // ── Scripted conversation with real ElevenLabs audio (audio on) ───────
  useEffect(() => {
    if (!audioOn || !active) return undefined;
    const line = SCRIPT[lineIdx];
    let cancelled = false;
    let timer: number | undefined;

    const advance = (delay: number) => {
      timer = window.setTimeout(() => {
        if (!cancelled) setLineIdx((i) => (i + 1) % SCRIPT.length);
      }, delay);
    };

    // Longer beat when the NEXT line starts a new section, so exchanges read as
    // separate one-topic-at-a-time blocks instead of running together.
    const next = SCRIPT[(lineIdx + 1) % SCRIPT.length];
    const gapAfter = next.section
      ? 1300
      : line.role === "lykn"
      ? 500
      : 400;

    // Play the current line's clip and move on when it finishes. The orb
    // reflects who is talking: "listening" while the human speaks, "speaking"
    // while LYKN replies.
    const playLine = () => {
      if (cancelled) return;
      setOrbState(line.role === "lykn" ? "speaking" : "listening");
      if (!line.src) {
        advance(fallbackLineMs(line.text));
        return;
      }
      const audio = new Audio(line.src);
      audioRef.current = audio;
      audio.onended = () => {
        if (!cancelled) advance(gapAfter);
      };
      audio.onerror = () => {
        if (!cancelled) advance(fallbackLineMs(line.text));
      };
      audio.play().catch(() => {
        // Autoplay blocked or load failed — keep the demo moving.
        if (!cancelled) advance(fallbackLineMs(line.text));
      });
    };

    if (line.role === "lykn") {
      // Brief "thinking" beat before LYKN answers.
      setOrbState("thinking");
      timer = window.setTimeout(playLine, 600);
    } else {
      playLine();
    }

    return () => {
      cancelled = true;
      if (timer) window.clearTimeout(timer);
      const a = audioRef.current;
      if (a) {
        try {
          a.pause();
          a.currentTime = 0;
        } catch {
          /* ignore */
        }
      }
    };
  }, [audioOn, active, lineIdx]);

  // Stop any audio + reset the conversation when sound turns off or the slide
  // goes inactive, so it always restarts cleanly from the top.
  useEffect(() => {
    if (audioOn && active) return undefined;
    setLineIdx(0);
    const a = audioRef.current;
    if (a) {
      try {
        a.pause();
        a.currentTime = 0;
      } catch {
        /* ignore */
      }
    }
    return undefined;
  }, [audioOn, active]);

  // Simulate a breathing mic amplitude while "listening" so the orb pulses.
  useEffect(() => {
    if (!active || orbState !== "listening") {
      setMicLevel(0);
      return undefined;
    }
    const start = performance.now();
    const tick = (now: number) => {
      const t = (now - start) / 1000;
      const v = 0.35 + Math.abs(Math.sin(t * 2.1)) * 0.5;
      setMicLevel(v);
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => {
      if (rafRef.current != null) cancelAnimationFrame(rafRef.current);
      rafRef.current = null;
    };
  }, [active, orbState]);

  const currentLine = audioOn ? SCRIPT[lineIdx] : null;
  // The section label persists across both lines of an exchange (only the
  // first line of each carries it).
  let currentSection: string | undefined;
  if (audioOn) {
    for (let i = lineIdx; i >= 0; i -= 1) {
      if (SCRIPT[i].section) {
        currentSection = SCRIPT[i].section;
        break;
      }
    }
  }

  return (
    <div className="relative flex h-full w-full flex-col items-center justify-center bg-background overflow-hidden">
      {allowAudio && (
        <button
          type="button"
          onClick={() => setAudioOn((on) => !on)}
          aria-pressed={audioOn}
          className="absolute top-4 right-4 z-10 inline-flex items-center gap-2 rounded-full border border-foreground/15 bg-foreground/5 px-3.5 py-2 text-xs font-medium text-foreground/80 backdrop-blur-sm transition-colors hover:bg-foreground/10"
          title={audioOn ? "Turn sound off" : "Turn sound on"}
        >
          {audioOn ? (
            <Volume2 className="h-4 w-4 text-blue-400" />
          ) : (
            <VolumeX className="h-4 w-4" />
          )}
          {audioOn ? "Sound on" : "Hear it"}
        </button>
      )}

      {/* The landing preview card is always dark, regardless of the visitor's
          app theme — force the white-dot palette so it never goes blue. */}
      <VoiceTechOrb state={orbState} micLevel={micLevel} size={320} appearance="dark" />

      <div className="mt-10 flex flex-col items-center gap-2 text-center max-w-xl px-6">
        {currentSection && (
          <span className="text-blue-400/80 text-[11px] font-semibold uppercase tracking-[0.18em]">
            {currentSection}
          </span>
        )}
        <span className="text-foreground/80 text-base font-medium">
          {STATUS_COPY[orbState] ?? "Listening…"}
        </span>
        {currentLine && (
          <p className="text-foreground/55 text-sm leading-relaxed">
            <span className="font-semibold text-foreground/70">
              {currentLine.role === "lykn" ? "LYKN" : "You"}:
            </span>{" "}
            {currentLine.text}
          </p>
        )}
        {allowAudio && (
          <span className="text-foreground/40 text-xs">
            {audioOn
              ? "Demo conversation · scripted sample voices"
              : "Tap “Hear it” for a sample demo conversation"}
          </span>
        )}
      </div>
    </div>
  );
}
