import { useEffect, useRef, useState } from "react";
import { Volume2, VolumeX } from "lucide-react";
import type { RealtimeVoiceState } from "@/hooks/useRealtimeVoice";
import VoiceTechOrb from "@/components/omnia/VoiceTechOrb";

interface WakeVoiceTourPreviewProps {
  active?: boolean;
}

// Same status copy the real Voice Mode overlay shows beneath the orb
// (OmniaVoiceModeEleven STATUS_COPY).
const STATUS_COPY: Partial<Record<RealtimeVoiceState, string>> = {
  idle: "Paused",
  connecting: "Connecting…",
  listening: "Listening…",
  thinking: "Thinking…",
  speaking: "Speaking…",
};

// A gentle scripted loop so the real orb feels alive in the walkthrough
// when audio is OFF (no mic / WebSocket session).
const SILENT_CYCLE: { state: RealtimeVoiceState; ms: number }[] = [
  { state: "connecting", ms: 1400 },
  { state: "listening", ms: 3200 },
  { state: "thinking", ms: 1600 },
  { state: "speaking", ms: 4200 },
];

// The scripted demo conversation. LYKN's lines are real audio clips rendered
// with the SAME ElevenLabs voice the live Voice agent uses (generated by
// scripts/generate-wake-voice-audio.mjs). User lines have no audio — in real
// Voice Mode you only ever HEAR LYKN; the user side is the mic — so they show
// as a caption with a short "listening" beat.
interface ScriptLine {
  role: "user" | "lykn";
  text: string;
  src?: string;
}

const SCRIPT: ScriptLine[] = [
  { role: "user", text: "Hey LYKN, what's on my plate today?" },
  {
    role: "lykn",
    text:
      "You have the investor call at two, and the Q3 brief is still open. Want me to pull the latest numbers and draft talking points?",
    src: "/wake-demo/voice/lykn-1.mp3",
  },
  { role: "user", text: "Yes, and keep working on it while I drive." },
  {
    role: "lykn",
    text:
      "On it. I've handed the research to a cloud agent. I'll have the brief saved to your vault before you arrive.",
    src: "/wake-demo/voice/lykn-2.mp3",
  },
];

// Rough reading time for the (audio-less) user lines.
const userLineMs = (text: string) =>
  Math.max(1600, text.split(/\s+/).filter(Boolean).length * 360);

/**
 * Walkthrough preview for Voice Mode. Renders the SAME VoiceTechOrb the real
 * Voice Mode overlay uses, in the same centered chrome. Audio is OFF by
 * default; a speaker toggle plays the scripted conversation, with LYKN voiced
 * by real ElevenLabs clips, and drives the orb state from playback.
 */
export default function WakeVoiceTourPreview({
  active = true,
}: WakeVoiceTourPreviewProps) {
  const [audioOn, setAudioOn] = useState(false);
  const [orbState, setOrbState] = useState<RealtimeVoiceState>("listening");
  const [micLevel, setMicLevel] = useState(0);
  const [lineIdx, setLineIdx] = useState(0);
  const [silentStep, setSilentStep] = useState(0);
  const rafRef = useRef<number | null>(null);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  // ── Silent idle animation (audio off) ────────────────────────────────
  useEffect(() => {
    if (audioOn || !active) return undefined;
    const { ms } = SILENT_CYCLE[silentStep];
    setOrbState(SILENT_CYCLE[silentStep].state);
    const id = window.setTimeout(
      () => setSilentStep((s) => (s + 1) % SILENT_CYCLE.length),
      ms,
    );
    return () => window.clearTimeout(id);
  }, [audioOn, active, silentStep]);

  // ── Scripted conversation with real ElevenLabs audio (audio on) ───────
  useEffect(() => {
    if (!audioOn || !active) return undefined;
    const line = SCRIPT[lineIdx];
    let cancelled = false;
    let timer: number | undefined;

    const advance = (delay: number) => {
      timer = window.setTimeout(() => {
        if (!cancelled) setLineIdx((i) => (i + 1) % SCRIPT.length);
      }, delay);
    };

    if (line.role === "user" || !line.src) {
      setOrbState("listening");
      advance(userLineMs(line.text));
    } else {
      // Brief "thinking" beat, then play LYKN's clip and follow it.
      setOrbState("thinking");
      timer = window.setTimeout(() => {
        if (cancelled) return;
        setOrbState("speaking");
        const audio = new Audio(line.src);
        audioRef.current = audio;
        audio.onended = () => {
          if (!cancelled) advance(550);
        };
        audio.onerror = () => {
          if (!cancelled) advance(900);
        };
        audio.play().catch(() => {
          // Autoplay blocked or load failed — keep the demo moving.
          if (!cancelled) advance(1400);
        });
      }, 600);
    }

    return () => {
      cancelled = true;
      if (timer) window.clearTimeout(timer);
      const a = audioRef.current;
      if (a) {
        try {
          a.pause();
          a.currentTime = 0;
        } catch {
          /* ignore */
        }
      }
    };
  }, [audioOn, active, lineIdx]);

  // Stop any audio + reset the conversation when sound turns off or the slide
  // goes inactive, so it always restarts cleanly from the top.
  useEffect(() => {
    if (audioOn && active) return undefined;
    setLineIdx(0);
    const a = audioRef.current;
    if (a) {
      try {
        a.pause();
        a.currentTime = 0;
      } catch {
        /* ignore */
      }
    }
    return undefined;
  }, [audioOn, active]);

  // Simulate a breathing mic amplitude while "listening" so the orb pulses.
  useEffect(() => {
    if (!active || orbState !== "listening") {
      setMicLevel(0);
      return undefined;
    }
    const start = performance.now();
    const tick = (now: number) => {
      const t = (now - start) / 1000;
      const v = 0.35 + Math.abs(Math.sin(t * 2.1)) * 0.5;
      setMicLevel(v);
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => {
      if (rafRef.current != null) cancelAnimationFrame(rafRef.current);
      rafRef.current = null;
    };
  }, [active, orbState]);

  const currentLine = audioOn ? SCRIPT[lineIdx] : null;

  return (
    <div className="relative flex h-full w-full flex-col items-center justify-center bg-background overflow-hidden">
      <button
        type="button"
        onClick={() => setAudioOn((on) => !on)}
        aria-pressed={audioOn}
        className="absolute top-4 right-4 z-10 inline-flex items-center gap-2 rounded-full border border-foreground/15 bg-foreground/5 px-3.5 py-2 text-xs font-medium text-foreground/80 backdrop-blur-sm transition-colors hover:bg-foreground/10"
        title={audioOn ? "Turn sound off" : "Turn sound on"}
      >
        {audioOn ? (
          <Volume2 className="h-4 w-4 text-blue-400" />
        ) : (
          <VolumeX className="h-4 w-4" />
        )}
        {audioOn ? "Sound on" : "Hear it"}
      </button>

      <VoiceTechOrb state={orbState} micLevel={micLevel} size={320} />

      <div className="mt-10 flex flex-col items-center gap-2 text-center max-w-xl px-6">
        <span className="text-foreground/80 text-base font-medium">
          {STATUS_COPY[orbState] ?? "Listening…"}
        </span>
        {currentLine && (
          <p className="text-foreground/55 text-sm leading-relaxed">
            <span className="font-semibold text-foreground/70">
              {currentLine.role === "lykn" ? "LYKN" : "You"}:
            </span>{" "}
            {currentLine.text}
          </p>
        )}
        {!audioOn && (
          <span className="text-foreground/40 text-xs">
            Tap “Hear it” for a sample conversation
          </span>
        )}
      </div>
    </div>
  );
}
