/**
 * Generated images that live on this device from the moment they exist.
 *
 * When the vault is local, `/api/ai/imagine-image` hands back raw bytes rather
 * than uploading them, so the renderer is the first and only place they land.
 * That creates a problem the cloud path never had: a blob directory with no
 * row is exactly what `blobs.findOrphans()` reports as garbage, so an image
 * the user is still looking at would be indistinguishable from debris.
 *
 * So every generation gets a real row, marked `kind: "generation"`. It stays
 * out of the vault (every list and count filters on `kind = "vault"`) and out
 * of search (an untitled, bodyless row produces no embeddable text), while
 * giving the store two things it needs: proof the blob is spoken for, and a
 * `created_at` for the sweep that eventually clears the ones nobody kept.
 *
 * Saving one to the vault is then a promotion rather than a copy — the vault
 * row reuses this id, so the bytes are already sitting in the right directory.
 */

import { localBlobUrl } from "./mediaUrl";
import { writeLocalBlob } from "./localBlobs";

/** `items.kind` for a generation nobody has saved yet. */
export const GENERATION_KIND = "generation";

interface GenerationBridge {
  putItem: (item: Record<string, unknown>) => Promise<any>;
  getItem: (id: string) => Promise<any>;
}

function bridge(): GenerationBridge {
  const store = (globalThis as any)?.window?.lykn?.store;
  if (!store?.putItem) throw new Error("local store bridge is unavailable");
  return store as GenerationBridge;
}

function unwrap<T>(response: any): T {
  if (!response) throw new Error("local store call failed");
  if (response.ok === false) throw new Error(response.error || "local store call failed");
  return response.data as T;
}

export interface LocalGeneration {
  /** Row id, blob directory name, and the id the vault row inherits on save. */
  id: string;
  /** Store-relative blob path, e.g. `<id>/original.png`. */
  path: string;
  /** `lykn-blob://` URL, ready for an `<img src>`. */
  url: string;
  mimeType: string;
  bytes: number;
}

function extensionFor(mimeType: string): string {
  const mime = String(mimeType || "").toLowerCase();
  if (mime.includes("jpeg") || mime.includes("jpg")) return "jpg";
  if (mime.includes("webp")) return "webp";
  return "png";
}

/** Decode base64 without round-tripping through a data URL. */
function blobFromBase64(base64: string, mimeType: string): Blob {
  const binary = atob(String(base64 || ""));
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return new Blob([bytes], { type: mimeType || "image/png" });
}

/**
 * Write freshly generated bytes to disk and claim them with a row.
 *
 * The row is written after the blob so a failed write never leaves a row
 * pointing at a file that is not there — the reverse ordering is recoverable
 * (the sweep collects it) and this one is not.
 */
export async function storeLocalGeneration(opts: {
  base64: string;
  mimeType?: string;
}): Promise<LocalGeneration> {
  const mimeType = String(opts.mimeType || "image/png");
  const id = crypto.randomUUID();
  const blob = blobFromBase64(opts.base64, mimeType);
  if (!blob.size) throw new Error("generated image was empty");

  const written = await writeLocalBlob(id, blob, {
    filename: `generation.${extensionFor(mimeType)}`,
    mimeType,
    variant: "original",
  });

  // Deliberately minimal: no title, content or tags, so the indexer finds
  // nothing embeddable and the row never surfaces in search.
  unwrap(
    await bridge().putItem({
      id,
      kind: GENERATION_KIND,
      blob_path: written.path,
      mime_type: mimeType,
      byte_size: written.bytes,
    }),
  );

  return { id, path: written.path, url: written.url, mimeType, bytes: written.bytes };
}

/**
 * Look up a generation the renderer only knows by id.
 *
 * Returns null once the sweep has collected it, or if the row was never a
 * generation in the first place — callers use that to fall back to
 * re-downloading rather than trusting a path that may not exist.
 */
export async function readLocalGeneration(id: string): Promise<LocalGeneration | null> {
  if (!id) return null;
  let row: any = null;
  try {
    row = unwrap<any>(await bridge().getItem(id));
  } catch {
    return null;
  }
  if (!row?.blob_path) return null;

  return {
    id: String(row.id),
    path: String(row.blob_path),
    url: localBlobUrl(row.blob_path) || "",
    mimeType: String(row.mime_type || "image/png"),
    bytes: Number(row.byte_size || 0),
  };
}
